project:
  name: "FaceFusionCpp"
  description: "High-Performance C++ Implementation of FaceFusion"
  version: "0.34.0"
  author: "CodingRookie"
  date: "2026-02-22"
  license: "GPL-3.0-or-later"
  repository: "https://github.com/CodingRookie98/faceFusionCpp"
