name: 'Setup CUDA (Windows)'
description: 'Install CUDA Toolkit, cuDNN and TensorRT on Windows'
inputs:
  cuda-version:
    description: 'CUDA version to install (e.g., 12.6.0)'
    required: false
    default: '12.6.0'
  cudnn-version:
    description: 'cuDNN version to install (e.g., 9.6.0.74)'
    required: false
    default: '9.6.0.74'
  tensorrt-version:
    description: 'TensorRT version to install (e.g., 10.7.0.23)'
    required: false
    default: '10.7.0.23'
runs:
  using: "composite"
  steps:
    - name: Install CUDA Toolkit
      shell: pwsh
      run: |
        choco install cuda --version ${{ inputs.cuda-version }} -y
        $versionParts = "${{ inputs.cuda-version }}".Split('.')
        $majorMinor = $versionParts[0] + "." + $versionParts[1]
        $cudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v$majorMinor"
        if (Test-Path $cudaPath) {
          echo "CUDA_PATH=$cudaPath" >> $env:GITHUB_ENV
          echo "$cudaPath\bin" >> $env:GITHUB_PATH
          echo "$cudaPath\libnvvp" >> $env:GITHUB_PATH
        } else {
          Write-Error "CUDA installation path not found: $cudaPath"
          exit 1
        }

    - name: Install cuDNN
      shell: pwsh
      run: |
        $cudnnVersion = "${{ inputs.cudnn-version }}"
        $url = "https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/cudnn-windows-x86_64-$cudnnVersion`_cuda12-archive.zip"
        $output = "cudnn.zip"
        Write-Host "Downloading cuDNN from $url"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath .
        $cudnnDir = Get-ChildItem -Directory -Filter "cudnn-windows-x86_64-*" | Select-Object -First 1
        $cudaPath = $env:CUDA_PATH
        Copy-Item -Path "$($cudnnDir.FullName)\bin\*" -Destination "$cudaPath\bin" -Force
        Copy-Item -Path "$($cudnnDir.FullName)\include\*" -Destination "$cudaPath\include" -Force
        Copy-Item -Path "$($cudnnDir.FullName)\lib\x64\*" -Destination "$cudaPath\lib\x64" -Force

    - name: Install TensorRT
      shell: pwsh
      run: |
        $trVersion = "${{ inputs.tensorrt-version }}"
        $cudaVersion = "12.6"
        $url = "https://developer.download.nvidia.com/compute/machine-learning/tensorrt/10.7.0/TensorRT-$trVersion.Windows.win10.cuda-$cudaVersion.zip"
        $output = "TensorRT.zip"
        Write-Host "Downloading TensorRT from $url"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath .
        $trDir = Get-ChildItem -Directory -Filter "TensorRT-*" | Select-Object -First 1
        $trPath = $trDir.FullName
        echo "TensorRT_ROOT=$trPath" >> $env:GITHUB_ENV
        echo "TENSORRT_ROOT=$trPath" >> $env:GITHUB_ENV
        echo "$trPath\lib" >> $env:GITHUB_PATH
        echo "$trPath\bin" >> $env:GITHUB_PATH
