#!/usr/bin/env python3
import os
import sys
import shutil
from pathlib import Path

# Add script directory to sys.path
script_dir = Path(__file__).parent.resolve()
sys.path.append(str(script_dir.parent))


def log(message, level="info"):
    colors = {
        "info": "\033[96m",  # Cyan
        "success": "\033[92m",  # Green
        "warning": "\033[93m",  # Yellow
        "error": "\033[91m",  # Red
        "reset": "\033[0m",
    }
    if sys.platform == "win32" and not os.environ.get("WT_SESSION"):
        pass
    print(f"{colors.get(level, colors['reset'])}{message}{colors['reset']}")


def main():
    project_root = script_dir.parent
    hooks_dir = project_root / ".git" / "hooks"

    if not hooks_dir.parent.exists():  # Check .git exists
        log("Error: .git directory not found. Is this a git repository?", "error")
        sys.exit(1)

    hooks_dir.mkdir(exist_ok=True)

    dest_hook = hooks_dir / "pre-commit"

    # Create the hook content
    # It needs to invoke python scripts/pre_commit_check.py
    # We should use a relative path or absolute path to python?
    # Usually "python" in path is enough.

    # We need a shell script for the hook
    hook_content = ""
    if sys.platform == "win32":
        # On Windows, git hooks can be shell scripts (run by bash included with git)
        hook_content = """#!/bin/sh
# Auto-generated by scripts/install_hooks.py

# Ensure we are in project root (git hooks usually run from root, but to be safe)
# The hook is running in .git/hooks/, we need to go up two levels? 
# Actually git hooks run with CWD as the root of the repo.

echo "Running pre-commit hook..."
python scripts/pre_commit_check.py
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo "Pre-commit check failed."
    exit 1
fi

exit 0
"""
    else:
        # Linux/Mac
        hook_content = """#!/bin/sh
# Auto-generated by scripts/install_hooks.py

echo "Running pre-commit hook..."
python3 scripts/pre_commit_check.py
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo "Pre-commit check failed."
    exit 1
fi

exit 0
"""

    try:
        with open(dest_hook, "w", newline="\n") as f:
            f.write(hook_content)

        # Make executable on Unix
        if sys.platform != "win32":
            import stat

            st = os.stat(dest_hook)
            os.chmod(dest_hook, st.st_mode | stat.S_IEXEC)

        log(f"Git pre-commit hook installed successfully at {dest_hook}", "success")
    except Exception as e:
        log(f"Failed to install hook: {e}", "error")
        sys.exit(1)


if __name__ == "__main__":
    main()
